### ISSUE TITLE
[C++ GMS]，why not use GPU ORB to detect and compute keypoints？ 

### ISSUE THREAD

**Issue by klob** [JiawangBian/GMS-Feature-Matcher#10]
I am confused about that I got less keypoints when I used GPU ORB to detect keypoints. opencv3.2.0

**Comment by JiawangBian** [comment]
I don't know the reason, but I am sure that the GPU implementation of ORB is not as good as the CPU version in OpenCV library.

**Comment by klob** [comment]
Thanks，I also found GPU_ORB crashed using Multithread.
