### ISSUE TITLE
编译通过运行错误

### ISSUE THREAD

**Issue by 827165496** [JiawangBian/GMS-Feature-Matcher#14]
运行至orb->detectAndCompute(img1, Mat(), kp1, d1);时，会产生异常，进而触发一个断点。。。我用的是opencv3，不知道为什么这个自带函数会出现错误，还望指教，之前在作者的主页下面看见过同样的问题

**Comment by JiawangBian** [comment]
opencv没装好，你重新下载一个试试。

**Comment by 827165496** [comment]
恩恩，谢谢您，问题已解决。还想请问一下，这个demo程序对输入的图片的大小、种类有什么要求么

**Comment by JiawangBian** [comment]
特征点的数量应该根据图像大小而定。我在里面写了resize。所以你可以输入任意图片

**Comment by 827165496** [comment]
非常感谢您的回答。我是一名学生，最近刚接触特征检测，一直很好奇类似您文章中那些算法比对的结果是怎么做出来的呢，还有就是如何检测正确匹配的比例呢？
