### ISSUE TITLE
ORB-GMS方案只能用BruteForce匹配吗？

### ISSUE THREAD

**Issue by 827165496** [JiawangBian/GMS-Feature-Matcher#15]
如题，ORB和BRIEF特征描述子是uchar型。所以是不是只能用BruteForce匹配，之前看您主页下面的介绍里说到了NN匹配，请问这是什么情况呢，不太了解烦请解答，十分感谢

**Comment by JiawangBian** [comment]
nearest-neighbor matching。好像flann也有binary的匹配方案。你可以试试。想要加速的话可以用gpu

**Comment by 827165496** [comment]
好的，谢谢啦。还有一个问题，就是我把GMS方案用opencv2.4.9运行，改掉了ORB提取那部分，编译通过了，但是执行会崩溃，请问您了解吗？

**Comment by JiawangBian** [comment]
用release模式。debug模式有时会出错，目前猜测是由于编译器检查越界时的问题。

**Comment by 827165496** [comment]
恩恩，您的原版GMS已经在cv2.4.9上调通了，谢谢您^_^不过在我自己工程里还是有问题-_-||最近比较忙，过段时间我整理一下操作步骤发上来吧，
