### ISSUE TITLE
Segmentation fault with demo.cpp and withScale=false, withRotation=true

### ISSUE THREAD

**Issue by catree** [JiawangBian/GMS-Feature-Matcher#17]
In demo.cpp, change
`num_inliers = gms.GetInlierMask(vbInliers, false, false);`
by
`num_inliers = gms.GetInlierMask(vbInliers, false, true);`
The segmentation fault seems to occur here:

> #0  gms_matcher::AssignMatchPairs (this=this@entry=0x7fffffffd390, GridType=GridType@entry=1) at src/GMS-Feature-Matcher/include/gms_matcher.h:326

**Comment by JiawangBian** [comment]
I've fixed this bug by setting a default scale (I forgot to do that when I changed codes last time...).
Feel free to tell me new issues if you find them.
Thanks very much.

**Comment by catree** [comment]
The issue is fixed.
Thanks.
