### ISSUE TITLE
全景照片　特殊处理？

### ISSUE THREAD

**Issue by happyfrank** [JiawangBian/GMS-Feature-Matcher#18]
您好，大神，谢谢您分享了您的代码，效果非常好。
我想问下，您之前用过ＧＭＳ对全景照片（spherical）做过处理吗？ 
如果做的话，您有什么好的意见和方法吗？

**Comment by JiawangBian** [comment]
不好意思，没有处理过全景图。

**Comment by happyfrank** [comment]
嗯 好的 谢谢。^v^
