### ISSUE TITLE
using with AKAZE?

### ISSUE THREAD

**Issue by antithing** [JiawangBian/GMS-Feature-Matcher#22]
Hi, and thanks for making this code available. I am running it with ORB features, and it works great, but I would like to test with AKAZE. When I switch though, I get hardly any matches. What can I change to use this code with AKAZE features?

Thanks!

**Comment by JiawangBian** [comment]
You can assign a low threshold for AKAZE features to produce rich feature points.

In GMS design, the more feature points, the better.

**Comment by antithing** [comment]
Thank you!
