### ISSUE TITLE
Can this method be used to improve accuracy?

### ISSUE THREAD

**Issue by Yajiang** [JiawangBian/GMS-Feature-Matcher#23]
Hello, thanks for your great work. Here I tried your method in my work, and I found that your method was more likely to be used to improve ORB features matching, while it didn't improve performance for AKAZE features matching. I have also read your paper, and here is my question.
This method can improve ORB features matching because it can produce a lot of features and those features sometimes cannot match well.So here the law of large numbers works. But for AKAZE matching, since it can match accurately at first, the law of large numbers cannot improve it any more. Am I right about this method?
I'll appreciate it if you can give me a reply.

**Comment by JiawangBian** [comment]
As the method depends on statistics to identify true or false matches, the performance relis on sample (match) numbers. ORB can provide much more matches, so the performance is robust. Actually, AKAZE matching performances could also be improved if you let it generate a large number of correspondences, e.g., decreasing some thresholds to accept more feature points.

**Comment by Yajiang** [comment]
Thanks for your reply! I have also tried AKAZE matching with a lower threshold. For an image 1024*512 it produced about 30000 features and actually it matched well. But the accuracy was a bit lower than ratio matching. Could you please share your opinion about this result ?

**Comment by JiawangBian** [comment]
You can always tune parameters (threshold_factor = 6 as default) to get a better trade-off between recall and precision. The best value of it may vary from one desciptor to another, and also depends on feature numbers. Good luck.

**Comment by Yajiang** [comment]
Yes, you are right. I tried some parameters again. And I got one better result in which I used more features. But you know, the time consuming was a bit unacceptable. I will try to tune parameters later to find a faster one. Again, thanks for your great work and your patience.
