### ISSUE TITLE
GMS在PC机耗时多长？

### ISSUE THREAD

**Issue by watertianyi** [JiawangBian/GMS-Feature-Matcher#26]
matches = cv.xfeatures2d.matchGMS(img1.shape, img2.shape, kp1, kp2, matches_all, withRotation=True, withScale=True,thresholdFactor=threshold)，这个算子耗时53ms，比单应性耗时还长，是什么回事呢？

**Comment by JiawangBian** [comment]
因为这个setting放慢了40倍（5倍来自withScale，8倍来自withRotation)。另外，如果用cpp的话应该会更快一点。
