### ISSUE TITLE
Improve running time

### ISSUE THREAD

**Issue by UannaFF** [JiawangBian/GMS-Feature-Matcher#27]
Hi, thanks for this contribution. I'm trying to use gms matcher in my project but it takes too long to finish every task. Do you have any recommendations to speed up the process?

**Comment by JiawangBian** [comment]
nearest neighbor matching is most time-consuming, but it could be accelerated by using GPU. Besides, you can change the feature numbers to be detected. 10K is roughtly sufficient for most applications.
