### ISSUE TITLE
matlab demo.m error

### ISSUE THREAD

**Issue by Heisenberg-C** [JiawangBian/GMS-Feature-Matcher#3]
您好，非常感谢您的工作，在编译完MexGMS.cpp之后(vs2015 C++ complier), 运行demo.m出现如下报错：
![image](https://user-images.githubusercontent.com/24985018/28497259-4febd68e-6fb6-11e7-8082-85db2bc93e26.png)

个人运行环境为：
visual studio 2015 professional
Matlab2015b

请问该如何解决呢？

**Comment by JiawangBian** [comment]
试试使用release
