### ISSUE TITLE
是否可以指定特征点

### ISSUE THREAD

**Issue by ffffwyy** [JiawangBian/GMS-Feature-Matcher#31]
我只需要捕捉几个特征点的距离，可不可以不需要全部匹配，进而提高速度？

**Comment by JiawangBian** [comment]
可以 ，但是点如果很稀疏就失去了统计意义，那gms的优势也没了，不过你可以根据你的情况试试

**Comment by ffffwyy** [comment]
好像不可以。我指定的点无法在另一个图片上进行匹配。貌似必须两幅图都通过orb自己找点。
