### ISSUE TITLE
关于准确率和召回率的问题

### ISSUE THREAD

**Issue by inoryJ** [JiawangBian/GMS-Feature-Matcher#33]
边老师，我最近也在研究特征匹配，很想知道怎么确定匹配点是否正确匹配，在网上搜索，有的人说某些开源数据集提供单应矩阵，通过单应矩阵的转换，判断是否匹配正确，但是我目前还没有找到，不知道您可不可以提供一些带有单应矩阵的数据集。

**Comment by JiawangBian** [comment]
http://www.robots.ox.ac.uk/~vgg/research/affine/

**Comment by inoryJ** [comment]
非常感谢老师！！！！！！太谢谢老师了!!!!


------------------ 原始邮件 ------------------
发件人: "JiaWang Bian"<notifications@github.com>;
发送时间: 2019年10月24日(星期四) 晚上8:25
收件人: "JiawangBian/GMS-Feature-Matcher"<GMS-Feature-Matcher@noreply.github.com>;
抄送: "李俊杰"<1065452558@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [JiawangBian/GMS-Feature-Matcher] 关于准确率和召回率的问题 (#33)




http://www.robots.ox.ac.uk/~vgg/research/affine/

**Comment by inoryJ** [comment]
非常感谢老师!!
