### ISSUE TITLE
Possible issue with vector index and mCellPairs[mvMatchPairs[i].first]

### ISSUE THREAD

**Issue by catree** [JiawangBian/GMS-Feature-Matcher#34]
This is to report a possible issue reported by a user in the following thread: https://github.com/opencv/opencv_contrib/issues/2437

More information about the issue should be asked to the original user.

Also, I don't know if the code in OpenCV contrib is up to date with this repository.

**Comment by JiawangBian** [comment]
Thanks for your info. I find that this has been fixed in current version, but not fixed in OpenCV library.

**Comment by catree** [comment]
Thanks.
Corresponding PR has been submitted: opencv/opencv_contrib#2451
