### ISSUE TITLE
关于不同尺度图片的匹配问题

### ISSUE THREAD

**Issue by Alexadlu** [JiawangBian/GMS-Feature-Matcher#35]
请问，将一张图片中目标区域裁剪出patch作为图片，这个patch是否可以和原图进行匹配，两个图片大小不一致能否进行匹配呢？
还有一个小问题：匹配完成后的匹配点对中，要怎样可以判断匹配的置信度最高的那个点对呢？或者说那几个点？

**Comment by JiawangBian** [comment]
1. 没有问题，把multi-scale=true就可以了。有看到过其他人做的demo。
2。 可以用 feature distance.

**Comment by Alexadlu** [comment]
谢谢您的回复。在使用过程中发现似乎对小目标的keypoint提取质量不高，或者说分辨率比较低的区域提取质量数量都不高，在这个领域一般都会有什么解决思路来提升小目标的keypoint提取性能呢

**Comment by Alexadlu** [comment]
python 版本中 似乎没有multi-scale=true这个选项，请问可以在哪里找到么

**Comment by JiawangBian** [comment]
https://docs.opencv.org/master/db/dd9/group__xfeatures2d__match.html 这里有

**Comment by JiawangBian** [comment]
分辨率低或者low-texture区域特征不明显。可以手动指定，但是提出来的特征也不好。一般可以把ORB的fast threshold设置到0，把特征数量设置特别大，比如100W。

**Comment by Alexadlu** [comment]
好的 非常感谢，我实验一下！

**Comment by Alexadlu** [comment]
谢谢，刚才按照您的方法实验了一下，似乎也还是没能提取到想要的特征点，这种尺寸差异的想用基于keypoint匹配的方法是否是比较困难的？还是说不太可行的。。。


实质上左上角的小patch是从大图中裁剪的，我还尝试了同尺寸下进行匹配，发现目标空间位置不同，竟然也会影响到匹配性能，这是什么原理。。还是我对keypoint理解有误：keypoint我的理解是具有较强鲁棒性的一个极小区域特征，在多种挑战下仍具有较强的可判别性。？


最后还想问一下这样的匹配问题，基于keypoint的方法是否不太容易实现。
期待您的回复，谢谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JiaWang Bian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 上午10:12
收件人:&nbsp;"JiawangBian/GMS-Feature-Matcher"<GMS-Feature-Matcher@noreply.github.com&gt;;
抄送:&nbsp;"今日"<1214670665@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JiawangBian/GMS-Feature-Matcher] 关于不同尺度图片的匹配问题 (#35)





 
分辨率低或者low-texture区域特征不明显。可以手动指定，但是提出来的特征也不好。一般可以把ORB的fast threshold设置到0，把特征数量设置特别大，比如100W。

**Comment by JiawangBian** [comment]
这样都不行就说明那片区域纹理太弱了。没法做特征匹配。

**Comment by Alexadlu** [comment]
嗯嗯好的，谢谢解答




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JiaWang Bian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 上午10:38
收件人:&nbsp;"JiawangBian/GMS-Feature-Matcher"<GMS-Feature-Matcher@noreply.github.com&gt;;
抄送:&nbsp;"今日"<1214670665@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JiawangBian/GMS-Feature-Matcher] 关于不同尺度图片的匹配问题 (#35)





 
这样都不行就说明那片区域纹理太弱了。没法做特征匹配。
