### ISSUE TITLE
[QUESTION] Comparing to thousands of images

### ISSUE THREAD

**Issue by filipemansano** [JiawangBian/GMS-Feature-Matcher#38]
I have a question, it is not well related to the algorithm itself, but how to best way use it in a specific scenario.

the algorithm worked very well when comparing 2 images, images that represent the same scenario regardless of angle, rotation, color, size ... the match was found successfully.

I am using the algorithm to detect duplicate images.

example 2 different images, one photo taken from the side and the other from the front of anyone object, both are different photos, but represent the same object in different positions

the question is: how to use the algorithm to compare an image against a database with thousands of other images to find a duplicate?

and if that image is not found in the database, it will be added as a new image, in this case I think I could not use BoW, because I would have to train it again with each image added to the database, right?

**Comment by JiawangBian** [comment]
1. Traditional feature matching can only match similar patterns, so that the side and the frount of an object could not be matched. 

2. you problem is called image retrieival. I think you may try recent deep learning based approaches, if images in the database are like 'side-front' cases.
