### ISSUE TITLE
matlab demo error

### ISSUE THREAD

**Issue by Candyeeee** [JiawangBian/GMS-Feature-Matcher#4]
Compile.m编译好之后，当前文件夹已经存在MexGMS.mexw64，依然报错：
Invalid MEX-file 'D:\Github\GMS-Feature-Matcher-master\matlab\MexGMS.mexw64': 找不到指定的模块。

请问是什么原因呢？

**Comment by JiawangBian** [comment]
把opencv的dll加入到系统路径。

**Comment by Candyeeee** [comment]
还是不行额大神，我的编译器是vs2010，试了两个版本，opencv300和opencv320，把dll都加到C-->windows-->System32，还是报了同样的错误
