### ISSUE TITLE
How did you get R and t from matches?

### ISSUE THREAD

**Issue by kmyi** [JiawangBian/GMS-Feature-Matcher#9]
Hello,

I am trying to reproduce your results for the strecha dataset, and was wondering if the benchmark code is available. Since their are hundreds of ways to get the R and the t from the matches, can you please let me know how you retrieved the pose? or the fundamental matrix? 

Cheers,
Kwang

**Comment by JiawangBian** [comment]
Hey,

You can use OpenCV function "findEssentialMat" and "recoverPose " to get R and t. The benchmark code is now partially available in my other repository "Image-Matching-Benchmark". I will update it step by step.

Best,
JiaWang

**Comment by kmyi** [comment]
Hello,

Did you use the default options for findEssentialMat in your experiments?
As the options do affect the results quite a lot.
For example, LMEDS and RANSAC give different results, as well as the RANSAC threshold having a big impact.

Cheers,
Kwang

**Comment by JiawangBian** [comment]
In GMS paper, we use a MATLAB code to compute R and t, which is not released for many reasons. However, if you want to evaluate your algorithm, I suggest that you can use the code in "Image-Matching-Benchmark", where I provide all that you need.

**Comment by kmyi** [comment]
Hi,

> I suggest that you can use the code in "Image-Matching-Benchmark", where I provide all that you need.

Unfortunately, we would like to test on a different dataset than yours, and without knowledge on how the essential matrix is extracted from the matches, we cannot have a fair comparison. Can you please detail the essential matrix computation? For example, if it's the Matlab version, only the norm8point option gives results that are without additional outlier rejection. Which is why we tried using your matches with the 8point algorithm and could not get proper R, t estimated. Do you use any additional outlier rejection on top?

Cheers,
Kwang

**Comment by JiawangBian** [comment]
I just use 5points method. You can use opencv functions with default thresholds. The whole estimation code of GMS is covered in the benchmark repository , and please check the folder “Algorithm”.

**Comment by kmyi** [comment]
I see... I've checked the code. So you are in fact using RANSAC on top. 

Thanks,
Kwang

**Comment by JiawangBian** [comment]
Yes, RANSAC
